### ISSUE TITLE
Can't BRUN file, cause exception instead.

### ISSUE THREAD

**Issue by Michaelangel007** [badvision/jace#10]
Pressing `Ctrl-Shift-B` is supposed to be able to `BRUN` a binary file.

I'm getting this crash ...

```
SEVERE: null
java.lang.IllegalArgumentException: argument type mismatch
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at jace.core.Keyboard$1.handleKeyDown(Keyboard.java:131)
	at jace.core.Keyboard.processKeyDownEvents(Keyboard.java:174)
	at jace.core.Keyboard.keyPressed(Keyboard.java:209)
	at jace.core.Keyboard.lambda$getListener$14(Keyboard.java:201)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Scene$KeyHandler.process(Scene.java:3964)
	at javafx.scene.Scene$KeyHandler.access$1800(Scene.java:3910)
	at javafx.scene.Scene.impl_processKeyEvent(Scene.java:2040)
	at javafx.scene.Scene$ScenePeerListener.keyEvent(Scene.java:2501)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification.run(GlassViewEventHandler.java:197)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification.run(GlassViewEventHandler.java:147)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleKeyEvent$353(GlassViewEventHandler.java:228)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleKeyEvent(GlassViewEventHandler.java:227)
	at com.sun.glass.ui.View.handleKeyEvent(View.java:546)
	at com.sun.glass.ui.View.notifyKey(View.java:966)

Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
	at jace.core.Keyboard$1.handleKeyDown(Keyboard.java:141)
	at jace.core.Keyboard.processKeyDownEvents(Keyboard.java:174)
	at jace.core.Keyboard.keyPressed(Keyboard.java:209)
	at jace.core.Keyboard.lambda$getListener$14(Keyboard.java:201)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Scene$KeyHandler.process(Scene.java:3964)
	at javafx.scene.Scene$KeyHandler.access$1800(Scene.java:3910)
	at javafx.scene.Scene.impl_processKeyEvent(Scene.java:2040)
	at javafx.scene.Scene$ScenePeerListener.keyEvent(Scene.java:2501)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification.run(GlassViewEventHandler.java:197)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification.run(GlassViewEventHandler.java:147)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleKeyEvent$353(GlassViewEventHandler.java:228)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleKeyEvent(GlassViewEventHandler.java:227)
	at com.sun.glass.ui.View.handleKeyEvent(View.java:546)
	at com.sun.glass.ui.View.notifyKey(View.java:966)
```

**Comment by badvision** [comment]
I think I can fix that pretty quickly -- would you like to be able to drag/drop the file as well?

**Comment by badvision** [comment]
Try renaming your files with this format:
name#06xxxx where xxxx is the load address of the program.  This is the extension used for Apple Game Server, and consequently was what this feature was meant to support once upon a time.

**Comment by Michaelangel007** [comment]
Drag/drop would be cool but it is a low priority for me.

I saw that the filename had to have a special syntax.  I guess I should have given more details:

 * I'm getting an error before the instant I press `Ctrl-Shift-B.`  

Q1. What exactly is the UI flow when an user presses `Ctrl-Shift-B` ?
Q2. How do I specify the filename to `BRUN`?  Is this on the command line?

**Comment by badvision** [comment]
You should see a file selector appear when you press ctrl+shift+B and after selecting said file, it should load into memory and the program counter is set to the start address.  Hence, the file has to include the load address.  I'll see if I can cause it to break but my early tests worked fine using the binary files in the apple game server (the java one, not the "online" one) lib folder.

**Comment by badvision** [comment]
Introspection issue in JRE 8.0.66 it looks like -- it was trying to call the wrong method via introspection.  I solved it by ensuring the method registered with the action is the only method with that specific name.

**Comment by badvision** [comment]
<img width="468" alt="screen shot 2016-01-14 at 9 31 23 pm" src="https://cloud.githubusercontent.com/assets/5144198/12344726/2b843fd6-bb06-11e5-9f50-bd58b256e2af.png">

**Comment by Michaelangel007** [comment]
Thanks for fixing this!

A proper BLOAD hotkey would be better (with aux support), but at lease I can BLOAD HGR images now even if they crash. =P
