### ISSUE TITLE
VideoDHGR doesn't work for me

### ISSUE THREAD

**Issue by Michaelangel007** [badvision/jace#7]
Using ...

* command line `-computer.video dhgr` or 
* `Configuration` > `Computer (Apple //e)` > `Renderer` with `VideoDHGR`

... causes this crash:

```
SEVERE: null
java.lang.IndexOutOfBoundsException: 588, 0
	at com.sun.prism.Image$BaseAccessor.getIndex(Image.java:933)
	at com.sun.prism.Image$BaseAccessor.setArgb(Image.java:978)
	at com.sun.prism.Image.setArgb(Image.java:647)
	at javafx.scene.image.WritableImage$2.setArgb(WritableImage.java:170)
	at javafx.scene.image.WritableImage$2.setColor(WritableImage.java:181)
	at jace.apple2e.VideoDHGR.showDhgr(VideoDHGR.java:624)
	at jace.apple2e.VideoDHGR.displayHires(VideoDHGR.java:330)
	at jace.apple2e.VideoDHGR$1.displayByte(VideoDHGR.java:87)
	at jace.apple2e.VideoDHGR.displayMixed(VideoDHGR.java:583)
	at jace.apple2e.VideoDHGR.access$400(VideoDHGR.java:43)
	at jace.apple2e.VideoDHGR$13.displayByte(VideoDHGR.java:259)
	at jace.core.Video.draw(Video.java:233)
	at jace.core.Video.tick(Video.java:168)
	at jace.core.Device.doTick(Device.java:89)
	at jace.core.Motherboard.tick(Motherboard.java:94)
	at jace.core.Device.doTick(Device.java:89)
	at jace.core.TimedDevice.lambda$resume$20(TimedDevice.java:94)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by badvision** [comment]
Oh it's kind of legacy and it produces crappy output anyway, it's the first renderer I wrote and it looks like holy hell.  I should probably remove it entirely except that the NTSC renderer subclasses it to add the NTSC/Video-7 support on top of the other stuff.

**Comment by badvision** [comment]
It's fixed now but switching requires you make the change, save changes, and then restart the emulator.  It sucks but it works now. :wink:
