### ISSUE TITLE
Using IDE raises exceptions

### ISSUE THREAD

**Issue by lifepillar** [badvision/jace#8]
The IDE in release 2.0b and in the current master does not work in OS X. Specifically, running Jace, pressing Ctrl-Shift-I and then choosing an item from the File menu raises an exception. For example, choosing File > New > Assembly Listing raises the following error:

```
Exception in thread "JavaFX Application Thread" netscape.javascript.JSException: ReferenceError: Can't find variable: CodeMirror
        at com.sun.webkit.dom.JSObject.fwkMakeException(JSObject.java:128)
        at com.sun.webkit.WebPage.twkExecuteScript(Native Method)
        at com.sun.webkit.WebPage.executeScript(WebPage.java:1439)
        at javafx.scene.web.WebEngine.executeScript(WebEngine.java:982)
        at jace.ide.Program.createEditor(Program.java:137)
        at jace.ide.Program.lambda$initEditor$130(Program.java:119)
        at com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(ExpressionHelper.java:182)
        at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
        at javafx.beans.property.ReadOnlyObjectWrapper$ReadOnlyPropertyImpl.fireValueChangedEvent(ReadOnlyObjectWrapper.java:176)
        at javafx.beans.property.ReadOnlyObjectWrapper.fireValueChangedEvent(ReadOnlyObjectWrapper.java:142)
        at javafx.beans.property.ObjectPropertyBase.markInvalid(ObjectPropertyBase.java:112)
        at javafx.beans.property.ObjectPropertyBase.set(ObjectPropertyBase.java:146)
        at javafx.scene.web.WebEngine$LoadWorker.updateState(WebEngine.java:1260)
        at javafx.scene.web.WebEngine$LoadWorker.dispatchLoadEvent(WebEngine.java:1371)
        at javafx.scene.web.WebEngine$LoadWorker.access$1200(WebEngine.java:1253)
        at javafx.scene.web.WebEngine$PageLoadListener.dispatchLoadEvent(WebEngine.java:1240)
        at com.sun.webkit.WebPage.fireLoadEvent(WebPage.java:2400)
        at com.sun.webkit.WebPage.fwkFireLoadEvent(WebPage.java:2244)
        at com.sun.webkit.network.URLLoader.twkDidFinishLoading(Native Method)
        at com.sun.webkit.network.URLLoader.notifyDidFinishLoading(URLLoader.java:838)
        at com.sun.webkit.network.URLLoader.lambda$didFinishLoading$96(URLLoader.java:829)
        at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
```

In some circumstances (apparently randomly) that results in Jace also hanging. Using OS X 10.11 and Java 1.8.0_66.

**Comment by badvision** [comment]
Thanks for the feedback!  That error indicates that CodeMirror (a javascript variable set up by an included javascript file) is not being set.  I've seen this happen in another java program in windows -- and I suspect there is some goofy behavior of the java classloader itself in more recent java builds where the classloader which is supposed to resolve things for the internal webkit engine fails to work in some cases!   Stay put, I'll try to reproduce this issue as time permits.

**Comment by badvision** [comment]
I confirmed it's the same issue I ran into with Outlaw Editor on Windows with a newer JDK.  The issue is that for whatever reason, someone made a bone-headed decision to change something and totally break the WebView's ability to load local resources: https://bugs.openjdk.java.net/browse/JDK-8136466
Solution: Use JRE 1.8.0.51 or older or use JRE 1.8.0.72 or newer.  1.8.0.65 and 1.8.0.66 are broken.

If you are a mac user, consider using "jenv" to simplify switching java environments.

**Comment by lifepillar** [comment]
I have installed Java 1.8.0_72 and, in fact, now the IDE works better. I can create new Assembly Listings, Plain Text, and Hex Data documents, but File > New > Applesoft Basic Listings still hangs Jace.

**Comment by badvision** [comment]
It will hang Jace if you are not already in Applesoft.  I need to work on that part a little more but essentially when you tell it to create a new basic program it tries to interpret the program you already have in memory.  Let's create a new issue for that bug though.
